# Generated by Django 3.2.10 on 2023-02-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_blog_id_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blog',
        ),
    ]
